version: '3.9'

services:
  php-environment:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 9001:80

  Mysql_db:
    image: mysql:lastest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: 123456
  
  phpmyadmin:
    image: phpmyadmin:5.2.0
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1